### ISSUE TITLE
Help with single pcb integration

### ISSUE THREAD

**Issue by EdenEast** [dpapavas/lagrange-keyboard#15]
I am working on adding support for adding [amoeba-royale](https://github.com/mtl/keyboard-pcbs/blob/master/amoeba-royale/amoeba-2.0-pinout.png) single pcb's to the model. I have copied the function that creates the keyswitch model and have it generating the pcb footprint.

```clojure
(defn switch-pcb [where, i j]
  (orient-keyswitch
   where, i j
   (union
     (color [0.2 0.2 0.3]
            (translate [0 0 -7]
                       (cube 18.1 20.1 3.5))))))
```

Adding this to the place keyswitch condition shows the pcbs rendering

```clojure
  (when place-keyswitches?
    (concat
    (key-placed-shapes keyswitch)
    (key-placed-shapes switch-pcb)
    (when build-thumb-section?
      (thumb-placed-shapes keyswitch)
      (thumb-placed-shapes switch-pcb)
      )))
```

<img width="451" alt="image" src="https://github.com/dpapavas/lagrange-keyboard/assets/2746374/dd714e97-5cee-4b92-aeaa-6cc3eefbaedc">

The issue I am having is when I try and use this as a cut tool. Every which way I try to take the difference of the connectors and the walls I get the following:

```
Exception in thread "main" java.lang.UnsupportedOperationException: nth not supported on this type: Keyword
```

<details>
<summary>Full exception</summary>
Exception in thread "main" java.lang.UnsupportedOperationException: nth not supported on this type: Keyword, compiling: form-init586412817069757682.clj:1:107)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.UnsupportedOperationException: nth not supported on this type: Keyword
        at clojure.lang.RT.nthFrom(RT.java:947)
        at clojure.lang.RT.nth(RT.java:897)
        at scad_clj.scad$eval4547$fn__4549.invoke(scad.clj:9)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at scad_clj.scad$write_block$fn__4572.invoke(scad.clj:25)
        at clojure.core$map$fn__4785.invoke(core.clj:2646)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:521)
        at clojure.core$seq__4357.invokeStatic(core.clj:137)
        at clojure.core$apply.invokeStatic(core.clj:641)
        at clojure.core$mapcat.invokeStatic(core.clj:2674)
        at clojure.core$mapcat.doInvoke(core.clj:2674)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at scad_clj.scad$write_block.invokeStatic(scad.clj:25)
        at scad_clj.scad$write_block.invoke(scad.clj:24)
        at scad_clj.scad$eval4761$fn__4763.invoke(scad.clj:197)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at scad_clj.scad$write_block$fn__4572.invoke(scad.clj:25)
        at clojure.core$map$fn__4785.invoke(core.clj:2646)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.boundedLength(RT.java:1749)
        at clojure.lang.RestFn.applyTo(RestFn.java:130)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$mapcat.invokeStatic(core.clj:2674)
        at clojure.core$mapcat.doInvoke(core.clj:2674)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at scad_clj.scad$write_block.invokeStatic(scad.clj:25)
        at scad_clj.scad$write_block.invoke(scad.clj:24)
        at scad_clj.scad$eval4812$fn__4814.invoke(scad.clj:240)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at scad_clj.scad$write_block$fn__4572.invoke(scad.clj:25)
        at clojure.core$map$fn__4785.invoke(core.clj:2646)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:521)
        at clojure.core$seq__4357.invokeStatic(core.clj:137)
        at clojure.core$apply.invokeStatic(core.clj:641)
        at clojure.core$mapcat.invokeStatic(core.clj:2674)
        at clojure.core$mapcat.doInvoke(core.clj:2674)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at scad_clj.scad$write_block.invokeStatic(scad.clj:25)
        at scad_clj.scad$write_block.invoke(scad.clj:24)
        at scad_clj.scad$eval4754$fn__4756.invoke(scad.clj:191)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at scad_clj.scad$eval4562$fn__4564$fn__4566.invoke(scad.clj:16)
        at clojure.core$map$fn__4785.invoke(core.clj:2646)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:521)
        at clojure.core$seq__4357.invokeStatic(core.clj:137)
        at clojure.core$apply.invokeStatic(core.clj:641)
        at clojure.core$mapcat.invokeStatic(core.clj:2674)
        at clojure.core$mapcat.doInvoke(core.clj:2674)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at scad_clj.scad$eval4562$fn__4564.invoke(scad.clj:16)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at scad_clj.scad$write_scad.invokeStatic(scad.clj:322)
        at scad_clj.scad$write_scad.doInvoke(scad.clj:321)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at lagrange_keyboard.core$_main.invokeStatic(core.clj:2552)
        at lagrange_keyboard.core$_main.doInvoke(core.clj:2503)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at user$eval5.invokeStatic(form-init586412817069757682.clj:1)
        at user$eval5.invoke(form-init586412817069757682.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
</details>

An example attemp:
```clojure
       (when (place-part? :top)
         (apply
          (if case-color (partial color case-color) union)
          (concat
           ;; Main section

           (apply difference
                  (apply union
                         @connectors (key-placed-shapes key-plate))
                  (key-placed-shapes switch-pcb))
```

The only clojure experience I have it messing with dactyl repos and trial and error.

Would you be able to give some guidance on this?

Thanks in advance,

**Comment by dpapavas** [comment]
To be honest, I haven't used Clojure or OpenSCAD, since I've finished this project, but show me your development branch, so that I can see and run your changes and I'll try to help out.

**Comment by EdenEast** [comment]
Thanks, my development branch is [switch-pcb](https://github.com/EdenEast/lagrange-keyboard/tree/switch-pcb). The current issue is that every time I try and call my `switch-pcb` in any context that uses `difference` or `union` I get the

```
nth not supported on this type: Keyword
```

**Comment by dpapavas** [comment]
The code in your last commit is slightly mixed up.  The way this works is this:  normally, you can say something like `(union A B C)` and the result will be the union of `A`, `B` and `C`, which are presumably `scad-clj` "shapes".  If you want to gather the parts dynamically, you can put them in a list and then `(apply union list-of-A-B-C)`, which is the same as the above, assuming `list-of-A-B-C)` contains `A`, `B` and `C`.

Your code has several problems.  First, your `(apply difference)` will take the difference of the parts that shoud be unioned.  Furthermore you've got the parts you actually want to subtract as a second argument to it, but that's not how it works.  Finally you have all of that inisde my code that takes the union of the parts that formed the keyboard.

The correct code should probably be something like this:

```clojure
(when (place-part? :top)
         (difference
          (apply
           (if case-color (partial color case-color) union)
           (concat
            ;; Main section

            @connectors (key-placed-shapes key-plate)

            ;; Thumb section

            (when build-thumb-section?
              (concat @thumb-connectors
                      (thumb-placed-shapes key-plate)))

            ;; Case walls

            (when-not (or thumb-test-build? key-test-build?)
                      (list*
                       (apply difference (apply union (case-placed-shapes screw-boss))
                              (case-placed-shapes screw-thread))
                       (case-placed-shapes (partial wall-brace wall-sections))))))
            (apply union
                   (concat
                    (key-placed-shapes switch-pcb)
                    (thumb-placed-shapes switch-pcb)))))
```

The code forming the first argument to `difference`, is my code, which unions the parts of the stock keyboard and forms the top.  Then the second argument is another union that forms the parts to cut out, i.e. the PCBs.  Note that, the PCB shapes are gathered into two lists via `key/thumb-placed-shapes`, which are then concatenated into one and have `union` appllied to them to form a single shape.  This is then subtracted from the stock part via `difference`.  (You could be a bit more clever and save yourself the union of the PCB's by using `(apply difference...`, but this way is easier to understand. )

The code above does run and produce an SCAD output file.  Whether it produces the desired results, I have no idea. :grin:

**Comment by EdenEast** [comment]
Awesome thanks for the explanation. It helps my understanding of how the code works. I could only get so far my trying to grock how Clojure and scad-clj worked. 

I resorted to creating a separate model with all the pcb's and using blender to perform the boolean difference operation. I could not find a good way to handle the inner most thumb  as well as what would be the `b` and `n` keys in `qwerty` without running into keycap clearance issues. For now I think I will just try and solder with the hotswap sockets themselves to at least keep the ability to hotswap.

In the meantime I tried to model a promicro holder as when I built my last dactly-manuform I ordered more then required for I have like 8 lying around. Gave up trying to model it in Clojure and did it in Fusion and used blender to assemble the parts together. Hope I can share a built keyboard soon.

**Comment by dpapavas** [comment]
Happy to hear you're making progress.  Make sure to post your build, either here, or in the relevant subreddits, etc.  Also, make sure to consider building the desktop clamp mount, once you've got the basic build working.  It works much better than one might assume at first glance.
